export const FETCH_DATA_REQUEST='FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS='FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE='FETCH_DATA_FAILURE';
export const REMOVE_DATA_FROM_MYCART='REMOVE_DATA_FROM_MYCART';
export const ADD_DATA_TO_MYCART='ADD_DATA_TO_MYCART';